### ISSUE TITLE
Configure script erroneously checks if certificate files exist when sslfilestype is path

### ISSUE THREAD

**Issue by FrankHomeSend** [ANSSI-FR/caml-crush#10]
The following code can be found in the configure.ac for caml-crush, which leads to the configure script checking the presence of client ssl certificates locally on the machine where compilation happens:
        # If the files are a path, put them in the makefiles
        if test "$sslfilestype" == "path"
        then
                # Check if the files exist, trigger an error if this is not the case
This does not make much sense in the use case where the caml-crush proxy daemon and client are run on different machines; My reason for using the 'path' option is to allow a more dynamic certificate usage compared to embedding the certificates (the use case where I'd expect the file check to happen).

Regards,
Frank

**Comment by tc-anssi** [comment]
Hi,

Good catch, we'll fix this shortly.

**Comment by tc-anssi** [comment]
Fixed in fc3c842.
Thanks.
