### ISSUE TITLE
Caml Crush with TLS is not working with Ocamlnet 4.x series

### ISSUE THREAD

**Issue by tc-anssi** [ANSSI-FR/caml-crush#13]
Upstream Ocamlnet TLS support was rewritten in the 4.x series.
The current Caml Crush server code must be heavily re-factored in order to be compatible with newer release of Ocamlnet.

However, this would remove the ocaml-ssl dependency and should provide more flexibility.

For now, this bug will serve as a placeholder towards achieving Ocamlnet 4.x TLS compatibility.

**Comment by tc-anssi** [comment]
Initial support in cb0abb1457a57ae2945ad656e319658402ed3c8c

**Comment by calderonth** [comment]
This has to be fixed, the Debian package in Sid is broken since the upgrade to Ocamlnet 4.x (bumped in mi-October).
