### ISSUE TITLE
Error RPC with C_SignInit in Apache on proxy daemon restart

### ISSUE THREAD

**Issue by FrankHomeSend** [ANSSI-FR/caml-crush#14]
When restarting the caml-crush proxy daemon, Apache's httpd fails to handle new TLS handshakes from MSIE 11 and Opera 12 web browsers.
On each connection attempt by the browser, the following line appears in the apache error log:
>Error RPC with C_SignInit

This error is fixed by restarting the Apache service, which for obvious reasons is not a feasible solution in high availability scenarios.

Tested:
>with SSL-encrypted PKCS11 calls between caml-crush proxy daemon and client library
>without SSL for the communication between caml-crush proxy daemon and client library
>with mod_gnutls 
>with mod_nss

**Comment by tc-anssi** [comment]
This is an expected behavior and not link to browser types.

When you stop the server daemon, existing RPC communications are severed.
Since, the client application (here Apache) is not signaled about this (there is no proper way to do this), it blindly tries to call the signature function, which fails.
Hence, even if there was a logic to automatically reconnect the client library with the server, the PKCS#11 "state" was lost, the C_SignInit would also fail.

How is it any different compared to restarting a DB server while the application is still running?
I do not see the link with high availability, could you be more specific?

**Comment by FrankHomeSend** [comment]
The link with high availability is as follows:
Imagine the caml-crush proxy daemon running on two nodes in a high availability cluster, with a shared IP that is moved two the active node. When one machine fails, the remaining node will configure the shared IP address on its ethernet interface in order to provide the proxy service on the shared IP address. However, currently, all the servers running Apache, that also use the caml-crush client library for accessing its RSA keys, need to be restarted in order to allow new https connections from Opera 12 or MS IE 11.
This would create a gap in time where no HTTPS connections are available, until the Apache process has been restarted.

in the post I mentioned MSIE and Opera12, as the same behaviour is not observed with Google Chrome; this last browser is able to initiate a new HTTPS session with Apache without requiring a restart of Apache.

Would it be possible somehow to force the same behaviour observed with Chrome, onto all other connecting clients (maybe its tied to the TLS cipher suite used by each browser)? 
Losing the HTTPS session (which I assume is tied to the PKCS #11 'state') would not be a big problem, as long as a new one can immediately be initiated without requiring a restart of Apache.

**Comment by tc-anssi** [comment]
If I understood correctly, you have the following scenario:
```
  Apache1 Apache2
     |   /
    VIP	
  MachineA	MachineB
     |		   |
  CamlCrush	CamlCrush
```
Maybe some of the "working" behavior were triggered while using different Apache TLS modules in your tests. Implementations might differ in error handling.
Namely, if upon receiving the `CKR_GENERAL_ERROR` after the VIP switch, a TLS module could re-initialize the whole library and instantiate a new PKCS#11 session which would restore the TLS functionality.

You can try to reproduce the working behavior with a simpler scenario where you only restart the daemon and isolate which Apache module handle it better.

**Comment by FrankHomeSend** [comment]
That image shows exactly the desired end-scenario, which has not been implemented yet. 

At the moment the HA node switchover behaviour is modeled by restarting the caml-crush proxy daemon on a single machine (no VIP, no HA cluster), in order to test how the various SSL implementations in Apache handle an interruption of communication with the PKCS11 module.

Unfortunately, it strongly appears that both mod_nss and mod_gnutls require a restart of the apache service in order to be able to handle new HTTPS sessions. If I understand you correctly, this is exactly the module where code changes would potentially allow a change of this behaviour?

Some semi-off-topic observations:
>mod_ssl never seems to have moved into the direction of being able to initialise an OpenSSL engine such as OpenSC' engine_pkcs11 (requires loading an OpenSSL CONF library configuration file), although I saw some initial patches proposed at http://markmail.org/message/hxdekbxzttdyhjpm
>It's surprising to say the least, that HSM manufacturers haven't filled this gap with patches to the upstream mod_ssl code... do they honestly treat this functionality as a product differentiator, keeping their own apache module as propriety code? I'd assume all the HSM on the market would cover the same apache functionality by now..
>on RHEL7.1 I strongly prefer mod_gnutls over mod_nss, as for some incomprehensible reason NSS (at least on RHEL) supports neither TLS 1.2 protocol nor DHE_RSA cipher suites. How can products be released in 2015 that don't support these features?

**Comment by tc-anssi** [comment]
Indeed, it seems patching Apache modules is mandatory to try to re-instantiate a PKCS#11 context. I have not thoroughly looked at the code, so I am unable to say if this is a simple or complicated fix.

Now regarding your semi-off-topic observations:
  * mod_ssl or OpenSSL never really moved towards a proper support of hardware devices. The "engine" support is in my opinion a mess. As you observed, there was little interest in merging a proper HSM support (PKCS#11 being the de-facto standard), which is sad.
  * I guess HSM manufacturers are satisfied with PKI use cases and probably lack vision for alternative deployment scenarios.
  * Again, good catch, NSS never bothered implementing the server-side of DHE-RSA. Patches are waiting to be merged (check https://bugzilla.mozilla.org/show_bug.cgi?id=102794). I do not know if it will ever happen, might be useful to raise your voice. TLS 1.2 is available in the release of mod_nss I use (Ubuntu 14.04 might have backported support). If it is not available in your mod_nss version, you are stuck with the ecdhe_rsa_aes_256_sha suite.

**Comment by FrankHomeSend** [comment]
Thanks for having confirmed the potential targets for a fix.

As for mod_nss on RHEL, I forgot to mention in my earlier post that it also doesn't support any cipher suite with SHA-2 algorithms for message when using it for server-side TLS. I haven't investigated if this is due to the fact that nss in RHEL 7.1 (3.16) is slightly behind the version in Ubuntu 14.04 (3.17), or if the Red Hat version is explicitly compiled without SHA-2 and TLS 1.2. Might look further into that issue at a later time, as for now, mod_gnutls already can do TLS 1.2, SHA-2 and DHE-RSA

**Comment by tc-anssi** [comment]
Now for your HA scenario, I think adapting your scenario could solve your issue:
```
    VIP	
  Apache1	Apache2
     |		   |
  MachineA	MachineB
     |		   |
  CamlCrush	CamlCrush
```
If the Caml-Crush instance cannot be reach, you can fence the Apache server and attach the VIP to the second one. Wouldn't this solve your HA issue?

**Comment by FrankHomeSend** [comment]
Thank you very much for your input.
Unfortunately, there are other constraints related to PCI-DSS scoping and co-habitation with Oracle products that have particular licensing requirements, that make this particular proposal less than optimal.
Right now at the top of my list is exploring the options for modifying mod_gnutls to provide a more graceful fail-over capability... 
if that is not feasible, alteration of the High-Availabilty configuration might be considered.

Regards,
Frank
