### ISSUE TITLE
Make error (configuration : ssl without filter)

### ISSUE THREAD

**Issue by WoBuGs** [ANSSI-FR/caml-crush#22]
When I try to make the project with these options : 
--with-idlgen
--with-rpcgen
--with-libnames=softhsm
--with-client-socket=tcp,192.168.212.76:4444
--with-ssl --with-ssl-clientfiles='path;ca=/root/pki/certificats/ca.crt,cert=/root/pki/certificats/caml-crushclient.crt,privkey=/root/pki/certificats/caml-crushclient.key'
--without-filter

I get the following compilation error : 
File "./server_ssl.ml", line 207, characters 25-40:
Error: This expression has type 'a option
       but an expression was expected of type string

But I works fine when I compile with ssl AND filter.

**Comment by rb-anssi** [comment]
Thanks for the bug report, this should be corrected in commit f2ae99a.
