### ISSUE TITLE
Build from source on Centos 7.2

### ISSUE THREAD

**Issue by Batouu** [ANSSI-FR/caml-crush#27]
Hi,

I'm having some trouble to build caml-crush on centOS 7.2 (1511).
I use these options with configure :
./configure --with-idlgen --with-rpcgen --with-libnames=softhsm --with-ssl
but i have an error during the checking phase : 
"checking Ocaml package rpc... configure: error: not found"

After some research, it would seem it needs libocamlnet / ocaml-camlnet packages. But i can't find them for centOS. 
What should i do ?

Thanks and regards,
Jeremy.

**Comment by calderonth** [comment]
Hello Batouu,

My guess is that you need to enable the EPEL repository to get the Ocamlnet
library.
Try running: yum install epel-release

This should enable the additional repository where you will find the
required library.

Best regards,

Thomas Calderon

**Comment by Batouu** [comment]
Thanks Thomas for your reply.

I already have enabled the EPEL repository without success.
I will try to build camlnet from sources.

Best regards,

Jeremy.

**Comment by calderonth** [comment]
Ah, they appear to be Fedora only.
You will also probably need to compile `coccinelle` from source.

**Comment by Batouu** [comment]
Okay. 
The version of ocaml that i am using is 4.0.1. 
Does caml-crush support this version ?

**Comment by calderonth** [comment]
Yes, Caml-Crush was compiled and tested against:
  - Caml 3.x/4.x
  - Ocamlnet 3.5+
  - Ocamlnet 4.0
Ocamlnet 4.1 should also work as the packages are working on Debian sid (using it).

**Comment by Batouu** [comment]
Okay, thanks. 
I'll give my feedback soon.

**Comment by Batouu** [comment]
Hi again,

I finaly achieve the installation of ocamlnet 4.1.2. I fixed it with an upper version of findlib (1.7).
However, i still got an issue during ./configure to build caml-crush :
"checking Ocaml package camlidl... configure: error: not found"

I tried to install camlidl from both, sources ( vers 1.05/1.04) and epl repository (vers 1.05 ) but still got this error.

Best regards,

Jeremy.

**Comment by calderonth** [comment]
What does the command `ocamlfind query camlidl` return?

**Comment by Batouu** [comment]
`ocamlfind: Package 'camlfind' not found`

Okay, so it would seem that there is an install path problem ?

**Comment by calderonth** [comment]
Please note that `camlidl` is included in EPEL, you should be able to install it with `yum install ocaml-camlidl`.

**Comment by Batouu** [comment]
Yeah, i've already done that. 
I will see if the problem comes from findlib-1.7 install path.

**Comment by Batouu** [comment]
Okay i fixed it by installing manualing `camlidl`. 
I found the `META.camlidl` file in bin/ocaml directory and installed it with `ocamlfind install` command.
The next step is coccinelle dependancies. I think i can handle it now.

**Comment by calderonth** [comment]
I have successfully compiled it on CentOS 7.2 in a Docker environment. You should be able to do so as well.

**Comment by Batouu** [comment]
Okay,
thanks for your help, i close this "issue".
