### ISSUE TITLE
Install on Centos 7

### ISSUE THREAD

**Issue by stephane-martin** [ANSSI-FR/caml-crush#31]
A few hints for folks working with Centos 7.

- Centos ships with gnutls compiled without SRP support. The ocamlnet compilation will fail because of that. I recompiled gnutls with SRP, some RPM/SRPM packages are available there: https://github.com/stephane-martin/gnutls-srp-centos7/releases

- It is much easier to get the Ocaml dependencies with opam. But the installation of opam is not so trivial, as the solver dependencies need a C++14 version of GCC. Of course the native GCC under Centos is not C++14. To bootstrap a Ocaml environment, you can use a prepackaged opam RPM from there: https://github.com/stephane-martin/opam-centos7/releases

- After installing the RPM, just do `opam init --comp 4.05.0` as a normal user to get Ocaml. Then you can `opam install whatyouwant`.

- camlcrush deps should be available through opam (camlidl, coccinelle, config-file, camlp4). Install them, also yum-install autoconf, make, gcc, ...

- camlcrush needs to find headers and library for camlidl. After you install camlidl with opam, make them available system-wide with:

`sudo ln -s /home/xxx/.opam/4.05.0/lib/camlidl/caml /usr/local/include`
`sudo ln -s /home/xxx/.opam/4.05.0/lib/camlidl/libcamlidl.a /usr/local/lib64`

- finally the normal build process for camlcrush should succeed.

**Comment by rb-anssi** [comment]
Stéphane,

Thanks for this feedback on CentOS!

Could you please move this content to a dedicated subsection in the CamlCrush Wiki by editing it, and close the issue?

Thanks in advance,

**Comment by stephane-martin** [comment]
Migrate to https://github.com/ANSSI-FR/caml-crush/wiki/Install-on-Centos-7
